### ISSUE TITLE
Promebuilder integration

### ISSUE THREAD

**Issue by debrando** [prometeia/pythowebdav#1]
> As a *developer*,
> I want *a standardize product lifecycle*
> so *I could just push my code as usual*.

--- 
##### Acceptance Criteria 01: push
*Given* I'm working on *develop* branch
*When* I push new work
*Then* a new alfa build is produced.

**Comment by debrando** [comment]
Test:

    # installazione locale
    conda create -n testpwdav pythowebdav
    conda activate testpwdav
    # avvio a servire a partire da C:\USERS con utenza pippo:pipo
    davserver -u pippo -p pippo -P 8080 -D C:\USERS

Sul browser diventa quindi navigabile in http://127.0.0.1:8080

**Comment by loredanaribatto** [comment]
testato su winscp funziona correttamente. Ci sono problemi con win explorer

**Comment by loredanaribatto** [comment]
per ora rilasciamo l'implementazione solo con integrazione winscp
