### ISSUE TITLE
Pythoauth integration

### ISSUE THREAD

**Issue by debrando** [prometeia/pythowebdav#2]
> As a *customer*,
> I want *the same account of related pytho platform*
> so *I could manage only one password and in the same way*.

--- 
##### Acceptance Criteria 01: login
*Given* I'm connectiong to my user area
*When* I try to login with my Pytho's password or token
*Then* I would connect seamless.

##### Acceptance Criteria 02: password change
*Given* I'm changing my Pytho's password
*When* access again to my user area
*Then* I would be soon asked to enter the new password.

**Comment by debrando** [comment]
Testabile su pythoalfa (cfr. issue del deploy).

**Comment by loredanaribatto** [comment]
Entrambi gli acceptance test sono soddisfatti
